import { FC } from 'react';
import Head from 'next/head';
import Navbar from './Navbar';

import style from './Layout.module.scss';

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>My-Catalogs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className={style['container']}>{children}</div>
    </>
  );
};

export default Layout;
